/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package windows;

import functions.SQLquerys;
import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelos.persona;

/**
 *
 * @author jony1
 */
public class agregarPersona extends javax.swing.JFrame {

    optionsMenu om;

    public void setOm(optionsMenu om) {
        this.om = om;
    }
    
    /**
     * Creates new form agregarPersona
     */
    public agregarPersona() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LBagregarNombre = new javax.swing.JLabel();
        TFagregarNombre = new javax.swing.JTextField();
        TFagregarApat = new javax.swing.JTextField();
        LBagregarApat = new javax.swing.JLabel();
        TFagregarAmat = new javax.swing.JTextField();
        LBagregarAmat = new javax.swing.JLabel();
        TFagregarTelefono = new javax.swing.JTextField();
        LBagregarTelefono = new javax.swing.JLabel();
        LBagregarFnac = new javax.swing.JLabel();
        DCfNac = new com.toedter.calendar.JDateChooser();
        BTagregar = new javax.swing.JButton();
        BTcancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 221, 222));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        LBagregarNombre.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        LBagregarNombre.setForeground(new java.awt.Color(0, 0, 0));
        LBagregarNombre.setText("Nombre");

        TFagregarNombre.setBackground(new java.awt.Color(208, 244, 232));

        TFagregarApat.setBackground(new java.awt.Color(208, 244, 232));

        LBagregarApat.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        LBagregarApat.setForeground(new java.awt.Color(0, 0, 0));
        LBagregarApat.setText("<HTML>Apellido<br>Paterno");

        TFagregarAmat.setBackground(new java.awt.Color(208, 244, 232));

        LBagregarAmat.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        LBagregarAmat.setForeground(new java.awt.Color(0, 0, 0));
        LBagregarAmat.setText("<HTML>Apellido<br>Materno");

        TFagregarTelefono.setBackground(new java.awt.Color(208, 244, 232));
        TFagregarTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFagregarTelefonoKeyTyped(evt);
            }
        });

        LBagregarTelefono.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        LBagregarTelefono.setForeground(new java.awt.Color(0, 0, 0));
        LBagregarTelefono.setText("Telefono");

        LBagregarFnac.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        LBagregarFnac.setForeground(new java.awt.Color(0, 0, 0));
        LBagregarFnac.setText("<HTML>Fecha de<br>Nacimiento");

        DCfNac.setDateFormatString("yyyy-MM-dd");

        BTagregar.setBackground(new java.awt.Color(52, 255, 99));
        BTagregar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BTagregar.setText("Agregar");
        BTagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTagregarActionPerformed(evt);
            }
        });

        BTcancelar.setBackground(new java.awt.Color(255, 0, 0));
        BTcancelar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BTcancelar.setText("Cancelar");
        BTcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTcancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LBagregarAmat, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(TFagregarAmat))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LBagregarApat, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(TFagregarApat))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LBagregarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(TFagregarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBagregarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBagregarFnac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DCfNac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TFagregarTelefono))))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(BTcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFagregarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBagregarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LBagregarApat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFagregarApat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LBagregarAmat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFagregarAmat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBagregarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFagregarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LBagregarFnac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DCfNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTcancelarActionPerformed
        dispose();
        om.setEnabled(true);
        om.show();
    }//GEN-LAST:event_BTcancelarActionPerformed

    private void BTagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTagregarActionPerformed
        try{
            if (TFagregarNombre.getText().isBlank() && TFagregarApat.getText().isBlank() || TFagregarAmat.getText().isBlank() || TFagregarTelefono.getText().isBlank() || DCfNac.getDate() == null) {
                JOptionPane.showMessageDialog(null, "Llena los datos necesarios, por favor");
            }else{
                Long.parseLong(TFagregarTelefono.getText());
                if (TFagregarTelefono.getText().length() < 10) {
                    throw new NumberFormatException();
                }
                persona.setNombre(TFagregarNombre.getText());
                persona.setaPat(TFagregarApat.getText());
                persona.setaMat(TFagregarAmat.getText());
                persona.setTelefono(TFagregarTelefono.getText());
                persona.setfNac(new SimpleDateFormat(DCfNac.getDateFormatString()).format(DCfNac.getDate()));
                if(SQLquerys.agregarPersona()){
                    dispose();
                    om.setEnabled(true);
                    om.CBagregarPersona.setModel(SQLquerys.personas());
                    om.CBeditarPersona.setModel(SQLquerys.personas());
                    om.CBagregarPersona.setSelectedItem(persona.getID()+" "+persona.getNombre());
                    om.show();
                }
            }
        }catch(NumberFormatException e){
            System.out.println("Error: "+e);
            JOptionPane.showMessageDialog(null, "Agregue un numero teleffonico valido");
        }catch(Exception e){
            System.out.println("Error: "+e);
        }
    }//GEN-LAST:event_BTagregarActionPerformed

    private void TFagregarTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFagregarTelefonoKeyTyped
        functions.functions.numbers(evt);
    }//GEN-LAST:event_TFagregarTelefonoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agregarPersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTagregar;
    private javax.swing.JButton BTcancelar;
    private com.toedter.calendar.JDateChooser DCfNac;
    private javax.swing.JLabel LBagregarAmat;
    private javax.swing.JLabel LBagregarApat;
    private javax.swing.JLabel LBagregarFnac;
    private javax.swing.JLabel LBagregarNombre;
    private javax.swing.JLabel LBagregarTelefono;
    private javax.swing.JTextField TFagregarAmat;
    private javax.swing.JTextField TFagregarApat;
    private javax.swing.JTextField TFagregarNombre;
    private javax.swing.JTextField TFagregarTelefono;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
