
package windows;

import functions.SQLquerys;
import functions.functions;
import index.index;
import javax.swing.*;
import java.awt.Color;
import java.awt.event.*;
import javax.swing.table.DefaultTableModel;
import modelos.*;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

public class mainWindow extends javax.swing.JFrame {

    optionsMenu om;
    private confirmarPago cp;
    boolean conf = false;
    
    public mainWindow() {
        initComponents();
        setLocationRelativeTo(null);
        try {
            LBshowUsuario.setText(usuarios.getNombre());
            setExtendedState(MAXIMIZED_BOTH);
            functions.setBg("src/images/logo.png", LBlogo);
            functions.time(LBtime);
            functions.soltarCb(CBproducto,CBsabores,TFprecio);
            CBproducto.setModel(SQLquerys.nameProd());
            AutoCompleteDecorator.decorate(CBproducto);
            AutoCompleteDecorator.decorate(CBsabores);
            CBproducto.getComponent(2).setBackground(new  Color(255,214,112));
            CBsabores.getComponent(2).setBackground(new  Color(255,214,112));
            
            if (usuarios.getTipo() == 3) {
                usuariosMenu.setVisible(false);
                articulosMenu.setVisible(false);
                cajaMenu.setVisible(false);
            }
            if (usuarios.getTipo() == 2) {
                cajaMenu.setVisible(false);
                usuariosMenu.setVisible(false);
            }
            
        } catch (Exception e) {
            System.err.println("Error: "+e);
        }
        
        
        //La funcion de abajo es para reafirmar que el usuario desea salir del programa
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                functions.salir();
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PMeliminarProducto = new javax.swing.JPopupMenu();
        MIeliminarProducto = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBproductos = new javax.swing.JTable();
        PNdatos = new javax.swing.JPanel();
        LBproducto = new javax.swing.JLabel();
        LBcantidad = new javax.swing.JLabel();
        LBprecio = new javax.swing.JLabel();
        TFprecio = new javax.swing.JTextField();
        LBlogo = new javax.swing.JLabel();
        BTagregar = new javax.swing.JButton();
        PNtotal = new javax.swing.JPanel();
        LBtotal = new javax.swing.JLabel();
        LBtotalPrice = new javax.swing.JLabel();
        LBsabores = new javax.swing.JLabel();
        CBsabores = new javax.swing.JComboBox<>();
        CBproducto = new javax.swing.JComboBox<>();
        SPcantidad = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        LBtime = new javax.swing.JLabel();
        LBusuario = new javax.swing.JLabel();
        LBshowUsuario = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        sesionMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        usuariosMenu = new javax.swing.JMenu();
        articulosMenu = new javax.swing.JMenu();
        cajaMenu = new javax.swing.JMenu();
        ayudaMenu = new javax.swing.JMenu();

        PMeliminarProducto.setBackground(new java.awt.Color(255, 0, 0));
        PMeliminarProducto.setForeground(new java.awt.Color(51, 255, 51));

        MIeliminarProducto.setBackground(new java.awt.Color(255, 0, 0));
        MIeliminarProducto.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        MIeliminarProducto.setForeground(new java.awt.Color(0, 0, 0));
        MIeliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/borrar.png"))); // NOI18N
        MIeliminarProducto.setText("Eliminar");
        MIeliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIeliminarProductoActionPerformed(evt);
            }
        });
        PMeliminarProducto.add(MIeliminarProducto);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(233, 255, 112));

        jScrollPane1.setMinimumSize(new java.awt.Dimension(350, 20));
        jScrollPane1.setOpaque(true);

        TBproductos.setAutoCreateRowSorter(true);
        TBproductos.setBackground(new java.awt.Color(255, 151, 112));
        TBproductos.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        TBproductos.setForeground(new java.awt.Color(2, 48, 71));
        TBproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Producto", "ID_sabor", "Sabor", "Precio", "Cantidad", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBproductos.setComponentPopupMenu(PMeliminarProducto);
        TBproductos.setMaximumSize(new java.awt.Dimension(2147483647, 4363456));
        TBproductos.setSelectionBackground(new java.awt.Color(142, 202, 230));
        TBproductos.setShowGrid(true);
        TBproductos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TBproductos);
        jScrollPane1.getViewport().setBackground(new java.awt.Color(2,48,71));
        if (TBproductos.getColumnModel().getColumnCount() > 0) {
            TBproductos.getColumnModel().getColumn(0).setMinWidth(0);
            TBproductos.getColumnModel().getColumn(0).setPreferredWidth(100);
            TBproductos.getColumnModel().getColumn(1).setMinWidth(0);
            TBproductos.getColumnModel().getColumn(1).setPreferredWidth(400);
            TBproductos.getColumnModel().getColumn(1).setMaxWidth(2500);
            TBproductos.getColumnModel().getColumn(2).setMinWidth(0);
            TBproductos.getColumnModel().getColumn(2).setPreferredWidth(0);
            TBproductos.getColumnModel().getColumn(2).setMaxWidth(0);
            TBproductos.getColumnModel().getColumn(3).setPreferredWidth(100);
            TBproductos.getColumnModel().getColumn(3).setMaxWidth(500);
            TBproductos.getColumnModel().getColumn(4).setPreferredWidth(100);
            TBproductos.getColumnModel().getColumn(5).setPreferredWidth(100);
            TBproductos.getColumnModel().getColumn(6).setPreferredWidth(150);
        }

        PNdatos.setBackground(new java.awt.Color(112, 214, 255));

        LBproducto.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        LBproducto.setForeground(new java.awt.Color(2, 48, 71));
        LBproducto.setText("Producto");

        LBcantidad.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        LBcantidad.setForeground(new java.awt.Color(2, 48, 71));
        LBcantidad.setText("Cantidad");

        LBprecio.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        LBprecio.setForeground(new java.awt.Color(2, 48, 71));
        LBprecio.setText("Precio");

        TFprecio.setBackground(new java.awt.Color(255, 214, 112));
        TFprecio.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        TFprecio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        TFprecio.setMinimumSize(new java.awt.Dimension(50, 25));
        TFprecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFprecioKeyTyped(evt);
            }
        });

        BTagregar.setBackground(new java.awt.Color(255, 151, 112));
        BTagregar.setText("AGREGAR");
        BTagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTagregarActionPerformed(evt);
            }
        });

        PNtotal.setBackground(new java.awt.Color(2, 48, 71));
        PNtotal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        PNtotal.setForeground(new java.awt.Color(0, 255, 255));
        PNtotal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PNtotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PNtotalMouseClicked(evt);
            }
        });

        LBtotal.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        LBtotal.setForeground(new java.awt.Color(255, 255, 255));
        LBtotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBtotal.setText("TOTAL");

        LBtotalPrice.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        LBtotalPrice.setForeground(new java.awt.Color(255, 255, 255));
        LBtotalPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBtotalPrice.setText("$0.00");

        javax.swing.GroupLayout PNtotalLayout = new javax.swing.GroupLayout(PNtotal);
        PNtotal.setLayout(PNtotalLayout);
        PNtotalLayout.setHorizontalGroup(
            PNtotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNtotalLayout.createSequentialGroup()
                .addComponent(LBtotal, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LBtotalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
        );
        PNtotalLayout.setVerticalGroup(
            PNtotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LBtotalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
            .addComponent(LBtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        LBsabores.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        LBsabores.setForeground(new java.awt.Color(2, 48, 71));
        LBsabores.setText("Sabor");

        CBsabores.setBackground(new java.awt.Color(255, 214, 112));
        CBsabores.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        CBsabores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        CBproducto.setBackground(new java.awt.Color(255, 214, 112));
        CBproducto.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        CBproducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        SPcantidad.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        SPcantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        SPcantidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        SPcantidad.setMaximumSize(new java.awt.Dimension(101, 25));
        SPcantidad.getEditor().getComponent(0).setBackground(new Color(255,214,112));

        javax.swing.GroupLayout PNdatosLayout = new javax.swing.GroupLayout(PNdatos);
        PNdatos.setLayout(PNdatosLayout);
        PNdatosLayout.setHorizontalGroup(
            PNdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNdatosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(PNdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PNtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PNdatosLayout.createSequentialGroup()
                        .addGroup(PNdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LBcantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LBproducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LBsabores))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PNdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PNdatosLayout.createSequentialGroup()
                                .addComponent(SPcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LBprecio)
                                .addGap(18, 18, 18)
                                .addComponent(TFprecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(CBsabores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CBproducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(15, 15, 15))
            .addGroup(PNdatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PNdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PNdatosLayout.setVerticalGroup(
            PNdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNdatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(PNdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(PNdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBsabores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CBsabores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(PNdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBprecio)
                    .addComponent(LBcantidad)
                    .addComponent(TFprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SPcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(BTagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(PNtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(112, 214, 255));

        LBtime.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 56)); // NOI18N
        LBtime.setForeground(new java.awt.Color(0, 0, 0));
        LBtime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBtime.setText("12:34");

        LBusuario.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 12)); // NOI18N
        LBusuario.setForeground(new java.awt.Color(2, 48, 71));
        LBusuario.setText("Usuario: ");

        LBshowUsuario.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 12)); // NOI18N
        LBshowUsuario.setForeground(new java.awt.Color(2, 48, 71));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(LBusuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LBshowUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LBtime, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LBtime, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBusuario)
                    .addComponent(LBshowUsuario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(112, 214, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(112, 214, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        menuBar.setPreferredSize(new java.awt.Dimension(279, 25));

        sesionMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/sesion.png"))); // NOI18N
        sesionMenu.setText("Sesion");
        sesionMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sesionMenu.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        sesionMenu.setMargin(new java.awt.Insets(2, 4, 2, 4));

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/close.png"))); // NOI18N
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        sesionMenu.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/userMenu.png"))); // NOI18N
        jMenuItem2.setText("Cambiar de usuario");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        sesionMenu.add(jMenuItem2);

        menuBar.add(sesionMenu);

        usuariosMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/usuario.png"))); // NOI18N
        usuariosMenu.setText("Usuarios");
        usuariosMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usuariosMenu.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        usuariosMenu.setMargin(new java.awt.Insets(2, 4, 2, 4));
        usuariosMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usuariosMenuMousePressed(evt);
            }
        });
        menuBar.add(usuariosMenu);

        articulosMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/productos.png"))); // NOI18N
        articulosMenu.setText("Productos");
        articulosMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        articulosMenu.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        articulosMenu.setMargin(new java.awt.Insets(2, 4, 2, 4));
        articulosMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                articulosMenuMousePressed(evt);
            }
        });
        menuBar.add(articulosMenu);

        cajaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/caja.png"))); // NOI18N
        cajaMenu.setText("Caja");
        cajaMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cajaMenu.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        cajaMenu.setMargin(new java.awt.Insets(2, 4, 2, 4));
        cajaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cajaMenuMouseClicked(evt);
            }
        });
        menuBar.add(cajaMenu);

        ayudaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/ayuda.png"))); // NOI18N
        ayudaMenu.setText("Ayuda");
        ayudaMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ayudaMenu.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        ayudaMenu.setMargin(new java.awt.Insets(2, 4, 2, 4));
        menuBar.add(ayudaMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(PNdatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PNdatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTagregarActionPerformed
        try {
            if (CBproducto.getSelectedIndex() != 0 && !TFprecio.getText().equals("")) {
                Double precio = Double.parseDouble(TFprecio.getText()); 
                if (precio != productos.getPrecio()) {
                    productos.setPrecio(precio);
                }
                System.out.println(CBsabores.getItemCount());
                if (CBsabores.getItemCount() > 0) {
                    sabor.setFlavor(CBsabores.getSelectedItem().toString());
                }else{sabor.setFlavor("");}

                functions.agregarProducto((DefaultTableModel) TBproductos.getModel(), (int) SPcantidad.getValue());

                LBtotalPrice.setText("$"+venta.getTotal());

                SPcantidad.setValue(1);
                TFprecio.setText("");
                CBproducto.setSelectedIndex(0);
                CBsabores.setModel(new DefaultComboBoxModel<>());
            }else{
                JOptionPane.showMessageDialog(null, "Llene los datos necesarios por favor");
            }
            
        } catch (Exception e) {
            System.err.println("Error: "+e);
        }
    }//GEN-LAST:event_BTagregarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        functions.salir();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void usuariosMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuariosMenuMousePressed
        om = new optionsMenu();
        om.setVisible(true);
        functions.ocultarLabels(om.PNusuarios, om.PNproductos, om.PNcaja);
        functions.botones(om.PNbotonUsuarios, om.PNbotonProductos, om.PNbotonCaja, 104,223,165);
        om.CBagregarPersona.setModel(SQLquerys.personas());
        om.CBeditarPersona.setModel(SQLquerys.personas());
        SQLquerys.llenarTablaUsuarios((DefaultTableModel) om.TBusuarios.getModel());
        this.setVisible(false);
    }//GEN-LAST:event_usuariosMenuMousePressed

    private void articulosMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_articulosMenuMousePressed
        om = new optionsMenu();
        om.setVisible(true);
        functions.ocultarLabels(om.PNproductos, om.PNusuarios, om.PNcaja);
        functions.botones(om.PNbotonProductos, om.PNbotonUsuarios, om.PNbotonCaja, 255,149,181);
        SQLquerys.llenarTablaProducto((DefaultTableModel) om.TBproductos.getModel());
        this.setVisible(false);
    }//GEN-LAST:event_articulosMenuMousePressed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        dispose();
        index ira = new index();
        ira.main(new String[]{});
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void TFprecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFprecioKeyTyped
        functions.numbers(evt);
    }//GEN-LAST:event_TFprecioKeyTyped

    private void PNtotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PNtotalMouseClicked

        if (TBproductos.getRowCount() > 0) {
            cp = new confirmarPago();
            cp.setTotal(Double.parseDouble(LBtotalPrice.getText().substring(1)));
            cp.setCantidad(venta.getTotalCantidad());
            cp.setTb(TBproductos);
            cp.setTotalPrice(LBtotalPrice);
            cp.setJf(this);
            cp.setVisible(true);
            cp.setLocationRelativeTo(null);
            setEnabled(false);
            System.out.println(caja.getCantidad());
        }
    }//GEN-LAST:event_PNtotalMouseClicked

    private void MIeliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIeliminarProductoActionPerformed
        functions.eliminarPVenta(TBproductos, this, LBtotalPrice);
    }//GEN-LAST:event_MIeliminarProductoActionPerformed

    private void cajaMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cajaMenuMouseClicked
        om = new optionsMenu();
        om.setVisible(true);
        functions.botones(om.PNbotonCaja, om.PNbotonUsuarios, om.PNbotonProductos, 204,244,252);
        functions.ocultarLabels(om.PNcaja, om.PNproductos, om.PNusuarios);
        SQLquerys.guardarcaja();
        SQLquerys.llenarTablaCajas((DefaultTableModel) om.TBcajas.getModel(), 0);
        this.setVisible(false);
    }//GEN-LAST:event_cajaMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTagregar;
    private javax.swing.JComboBox<String> CBproducto;
    private javax.swing.JComboBox<String> CBsabores;
    private javax.swing.JLabel LBcantidad;
    private javax.swing.JLabel LBlogo;
    private javax.swing.JLabel LBprecio;
    private javax.swing.JLabel LBproducto;
    private javax.swing.JLabel LBsabores;
    private javax.swing.JLabel LBshowUsuario;
    private javax.swing.JLabel LBtime;
    private javax.swing.JLabel LBtotal;
    private javax.swing.JLabel LBtotalPrice;
    private javax.swing.JLabel LBusuario;
    private javax.swing.JMenuItem MIeliminarProducto;
    private javax.swing.JPopupMenu PMeliminarProducto;
    private javax.swing.JPanel PNdatos;
    private javax.swing.JPanel PNtotal;
    private javax.swing.JSpinner SPcantidad;
    private javax.swing.JTable TBproductos;
    private javax.swing.JTextField TFprecio;
    private javax.swing.JMenu articulosMenu;
    private javax.swing.JMenu ayudaMenu;
    private javax.swing.JMenu cajaMenu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu sesionMenu;
    private javax.swing.JMenu usuariosMenu;
    // End of variables declaration//GEN-END:variables
}
